jobs:
- name: a-job
  public: true
  plan:
  - task: do-something
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: sh
        args:
        - -c
        - |
          echo "hi"

